#include <DataPrecisionGlobals.hh>
#include <OutputProcessor.hh>
#include <SpawnSurgicalTools.hh>

namespace SpawnSurgicalTools {
	Real64 reportingValue; // this is just the integrated value
	Real64 integrateDummyODE( Real64 initialValue, Real64 timestep )
	{
		static bool oneTimeFlag( true );
		if ( oneTimeFlag ) {
			EnergyPlus::SetupOutputVariable( "Spawn Surgery Dummy Integrated Value[]", reportingValue, "System", "Average", "Edwin" );
			oneTimeFlag = false;
		}
		// euler integration
		Real64 derivative = getTimeDerivative();
		reportingValue = initialValue + derivative * timestep;;
		return reportingValue;
	}

	Real64 getTimeDerivative()
	{
		return 1;  // random number, generated by roll of dice once
	}
}
